
anyNameTT<localizes><public>:message=
{"The name for this object, has no internal use."}

anyDescriptionTT<localizes><public>:message=
{"The description for this object, has no internal use."}


anyDescriptorTT<localizes><public>:message=
{"Describes the most basic parts of an object such as: Name, Description & Icon."}
    

anyCostTT<localizes><public>:message=
{"The cost for this object."}


    