
anyNameTT<localizes><public>:message=
{"The name for this object, has no internal use."}

anyDescriptionTT<localizes><public>:message=
{"The description for this object, has no internal use."}


anyDetailsTT<localizes><public>:message=
{"Describes the most basic parts of an object such as: Name, Description & Icon."}
    
anyCostTT<localizes><public>:message=
{"The cost for this object."}

anyCurrencyIDTT<localizes><public>:message=
{"Specifies the currency ID for this object."}
    

anyPersistableTT<localizes><public>:message=
{"If true, the object will have the ability to save and load data if and only if it's connected base has a Persister properly setup."}