#Base Tool Tips
BasesTT<localizes><public>:message=
{"The list of all bases in your game."}


#Purchaseable Tool Tips
PurchaseableIconTT<localizes><public>:message=
{"The icon for this purchaseable, will be displayed in any relevant UI."}
    
PurchaseZoneTT<localizes><public>:message=
{"The zone in which this purchaseable can be bought."}


#Unique Zone Tool Tips
TransmitOnEntryTT<localizes><public>:message=
{"The triggers that will be activated when an agent enters the zone."}

TransmitOnExitTT<localizes><public>:message=
{"The triggers that will be activated when an agent exits the zone."}



